object Versions {
    const val kotlinVersion = "1.4.21"
    const val serializationVersion = "1.0.1"
    const val hiltVersion = "2.38.1"
    const val hiltWorkManagerVersion = "1.0.0"
    const val workManagerVersion = "2.5.0"
    const val okHttpVersion = "4.9.0"
    const val coroutineVersions = "1.4.2"
    const val navigationVersion = "2.3.5"
    const val startUpVersion = "1.1.0"
    const val coreKtxVersion = "1.6.0"
    const val materialVersion = "1.4.0"
    const val junitVersion = "4.13"
    const val androidJunitExtensionVersion = "1.1.3"
    const val appCompatVersion = "1.3.1"
    const val constraintLayoutVersion =  "2.1.0"
    const val lifeCycleVersion = "2.3.1"
    const val espressoVersion = "3.4.0"
    const val roomVersion = "2.3.0-alpha04"
}